import * as fs from 'node:fs';
import * as path from 'node:path';
import { MANAGED_HEADER_PREFIX } from '../types.js';

/**
 * Read the package version from package.json.
 * Walks up from __dirname to find package.json.
 */
export function getPackageVersion(): string {
  // When bundled by tsup, __dirname is the dist/ folder.
  // package.json is one level up.
  const candidates = [
    path.resolve(__dirname, '..', 'package.json'),
    path.resolve(__dirname, 'package.json'),
    path.resolve(process.cwd(), 'package.json'),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(candidate, 'utf-8')) as {
          name?: string;
          version?: string;
        };
        if (pkg.name === '@he3-org/concert' && pkg.version) {
          return pkg.version;
        }
      } catch {
        continue;
      }
    }
  }
  return '0.0.0';
}

/**
 * Extract the version from a managed file header.
 * Looks for "AUTO-GENERATED BY CONCERT vX.Y.Z" in the first 5 lines.
 * Returns null if no version header is found.
 */
export function extractHeaderVersion(content: string): string | null {
  const lines = content.split('\n').slice(0, 5);
  for (const line of lines) {
    const match = line.match(/AUTO-GENERATED BY CONCERT v(\d+\.\d+\.\d+)/);
    if (match?.[1]) {
      return match[1];
    }
  }
  return null;
}

/**
 * Compare two semver version strings.
 * Returns: -1 if a < b, 0 if a == b, 1 if a > b.
 */
export function compareVersions(a: string, b: string): -1 | 0 | 1 {
  const partsA = a.split('.').map(Number);
  const partsB = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    const va = partsA[i] ?? 0;
    const vb = partsB[i] ?? 0;
    if (va < vb) return -1;
    if (va > vb) return 1;
  }
  return 0;
}

/**
 * Check if a file needs updating based on its header version.
 * Returns true if the file has no header or has an older version.
 */
export function needsUpdate(fileContent: string, currentVersion: string): boolean {
  const fileVersion = extractHeaderVersion(fileContent);
  if (fileVersion === null) return true; // No header = always update
  return compareVersions(fileVersion, currentVersion) < 0;
}

/**
 * Check if a file is managed by Concert (has the managed header).
 */
export function isManagedFile(content: string): boolean {
  const firstLines = content.split('\n').slice(0, 5).join('\n');
  return firstLines.includes(MANAGED_HEADER_PREFIX);
}
