import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { copyTemplates, copyManagedFiles, countTemplateFiles } from '../lib/copy.js';

let tmpSrc: string;
let tmpTarget: string;

beforeEach(() => {
  tmpSrc = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-copy-src-'));
  tmpTarget = fs.mkdtempSync(path.join(os.tmpdir(), 'concert-copy-target-'));
  // Create some test files in src
  fs.mkdirSync(path.join(tmpSrc, 'subdir'), { recursive: true });
  fs.writeFileSync(path.join(tmpSrc, 'file1.txt'), 'content 1');
  fs.writeFileSync(path.join(tmpSrc, 'file2.txt'), 'content 2');
  fs.writeFileSync(path.join(tmpSrc, 'subdir', 'file3.txt'), 'content 3');
});

afterEach(() => {
  fs.rmSync(tmpSrc, { recursive: true, force: true });
  fs.rmSync(tmpTarget, { recursive: true, force: true });
});

describe('copyTemplates', () => {
  it('copies all files from source to empty target', () => {
    const result = copyTemplates(tmpSrc, tmpTarget);
    expect(result.created).toHaveLength(3);
    expect(result.skipped).toHaveLength(0);
    expect(result.overwritten).toHaveLength(0);
    expect(fs.existsSync(path.join(tmpTarget, 'file1.txt'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'file2.txt'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'subdir', 'file3.txt'))).toBe(true);
  });

  it('skips existing files when overwrite is false', () => {
    // Pre-create one file
    fs.writeFileSync(path.join(tmpTarget, 'file1.txt'), 'existing content');
    const result = copyTemplates(tmpSrc, tmpTarget, false);
    expect(result.created).toHaveLength(2);
    expect(result.skipped).toHaveLength(1);
    expect(result.overwritten).toHaveLength(0);
    // Original content should remain
    expect(fs.readFileSync(path.join(tmpTarget, 'file1.txt'), 'utf-8')).toBe('existing content');
  });

  it('overwrites existing files when overwrite is true', () => {
    fs.writeFileSync(path.join(tmpTarget, 'file1.txt'), 'old content');
    const result = copyTemplates(tmpSrc, tmpTarget, true);
    expect(result.overwritten).toHaveLength(1);
    expect(fs.readFileSync(path.join(tmpTarget, 'file1.txt'), 'utf-8')).toBe('content 1');
  });

  it('creates nested directories', () => {
    const result = copyTemplates(tmpSrc, tmpTarget);
    expect(fs.existsSync(path.join(tmpTarget, 'subdir'))).toBe(true);
    expect(result.created.some((f) => f.includes('file3'))).toBe(true);
  });
});

describe('copyManagedFiles', () => {
  it('only overwrites files with managed headers', () => {
    const managedContent =
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nmanaged content';
    const userContent = '# User file\nuser content';
    fs.writeFileSync(path.join(tmpSrc, 'managed.md'), managedContent);
    fs.writeFileSync(
      path.join(tmpSrc, 'user.md'),
      '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nnew content'
    );
    // Pre-create target files
    fs.writeFileSync(path.join(tmpTarget, 'managed.md'), managedContent);
    fs.writeFileSync(path.join(tmpTarget, 'user.md'), userContent);
    const result = copyManagedFiles(tmpSrc, tmpTarget);
    // managed.md should be overwritten (it has managed header in target)
    expect(result.overwritten.some((f) => f.includes('managed.md'))).toBe(true);
    // user.md should NOT be overwritten (no managed header in target)
    expect(result.skipped.some((f) => f.includes('user.md'))).toBe(true);
    // user.md content should remain unchanged
    expect(fs.readFileSync(path.join(tmpTarget, 'user.md'), 'utf-8')).toBe(userContent);
  });

  it('skips files without managed headers', () => {
    fs.writeFileSync(path.join(tmpSrc, 'normal.txt'), 'new content');
    fs.writeFileSync(path.join(tmpTarget, 'normal.txt'), 'original');
    const result = copyManagedFiles(tmpSrc, tmpTarget);
    expect(result.skipped).toContain('normal.txt');
    expect(fs.readFileSync(path.join(tmpTarget, 'normal.txt'), 'utf-8')).toBe('original');
  });

  it("creates new files that don't exist in target", () => {
    fs.writeFileSync(path.join(tmpSrc, 'new-file.md'), 'new content');
    const result = copyManagedFiles(tmpSrc, tmpTarget);
    expect(result.created.some((f) => f.includes('new-file.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmpTarget, 'new-file.md'))).toBe(true);
  });
});

describe('countTemplateFiles', () => {
  it('correctly counts files by category', () => {
    fs.mkdirSync(path.join(tmpSrc, 'agents'), { recursive: true });
    fs.mkdirSync(path.join(tmpSrc, 'workflows'), { recursive: true });
    fs.writeFileSync(path.join(tmpSrc, 'agents', 'agent1.md'), 'agent 1');
    fs.writeFileSync(path.join(tmpSrc, 'agents', 'agent2.md'), 'agent 2');
    fs.writeFileSync(path.join(tmpSrc, 'workflows', 'wf1.md'), 'workflow 1');
    const counts = countTemplateFiles(tmpSrc);
    expect(counts['agents']).toBe(2);
    expect(counts['workflows']).toBe(1);
  });

  it('excludes .gitkeep files from counts', () => {
    fs.mkdirSync(path.join(tmpSrc, 'missions'), { recursive: true });
    fs.writeFileSync(path.join(tmpSrc, 'missions', '.gitkeep'), '');
    const counts = countTemplateFiles(tmpSrc);
    expect(counts['missions']).toBeUndefined();
  });
});
