import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as jsonc from "jsonc-parser";

const ROOT = path.resolve(__dirname, "../..");
const TEMPLATES_DIR = path.join(ROOT, "templates");

// ======================================================================
// 1. Directory structure
// ======================================================================

describe("templates directory structure", () => {
  const expectedDirs = [
    "templates/docs/concert/agents",
    "templates/docs/concert/workflows",
    "templates/docs/concert/skills",
    "templates/docs/concert/missions",
    "templates/.github/agents",
    "templates/.github/workflows",
    "templates/.claude/commands",
  ];

  for (const dir of expectedDirs) {
    it(`${dir} exists`, () => {
      expect(fs.existsSync(path.resolve(ROOT, dir))).toBe(true);
    });
  }
});

// ======================================================================
// 2. Agent definition files
// ======================================================================

const EXPECTED_AGENTS = [
  "concert-init",
  "concert-analyst",
  "concert-architect",
  "concert-designer",
  "concert-planner",
  "concert-coder",
  "concert-code-reviewer",
  "concert-reviewer",
  "concert-continue",
  "concert-status",
  "concert-debug",
  "concert-verifier",
  "concert-quick",
  "concert-push",
  "concert-documenter",
];

describe("agent definition files", () => {
  for (const agent of EXPECTED_AGENTS) {
    it(`${agent}.md exists with managed header and frontmatter`, () => {
      const filePath = path.join(TEMPLATES_DIR, "docs", "concert", "agents", `${agent}.md`);
      expect(fs.existsSync(filePath)).toBe(true);
      const content = fs.readFileSync(filePath, "utf-8");
      expect(content).toMatch(/<!-- AUTO-GENERATED BY CONCERT/);
      expect(content).toContain("name:");
      expect(content).toContain("description:");
      expect(content).toContain("tools:");
      expect(content).toContain("model:");
      expect(content).toContain("interactive_only:");
    });
  }
});

// ======================================================================
// 3. GitHub agent stubs
// ======================================================================

describe("GitHub agent stubs", () => {
  for (const agent of EXPECTED_AGENTS) {
    it(`${agent}.agent.md exists with correct format`, () => {
      const stubPath = path.join(TEMPLATES_DIR, ".github", "agents", `${agent}.agent.md`);
      expect(fs.existsSync(stubPath)).toBe(true);
      const content = fs.readFileSync(stubPath, "utf-8");
      expect(content).toMatch(/<!-- AUTO-GENERATED BY CONCERT/);
      expect(content).toContain("name:");
      expect(content).toContain("description:");
      expect(content).not.toContain("tools:");
      expect(content).not.toContain("\nmodel:");
      expect(content).toContain(`docs/concert/agents/${agent}.md`);
    });
  }
});

// ======================================================================
// 4. Claude Code command files
// ======================================================================

const EXPECTED_COMMANDS = ["init","plan","review","accept","status","continue","debug","verify","quick","push","restart","replan"];

describe("Claude Code command files", () => {
  for (const cmd of EXPECTED_COMMANDS) {
    it(`${cmd}.md exists with managed header`, () => {
      const cmdPath = path.join(TEMPLATES_DIR, ".claude", "commands", `${cmd}.md`);
      expect(fs.existsSync(cmdPath)).toBe(true);
      const content = fs.readFileSync(cmdPath, "utf-8");
      expect(content).toMatch(/<!-- AUTO-GENERATED BY CONCERT/);
    });
  }
});

// ======================================================================
// 5. Workflow files
// ======================================================================

const EXPECTED_WORKFLOWS = ["CONCERT-WORKFLOW-MISSION-FULL","CONCERT-WORKFLOW-MISSION-MEDIUM","CONCERT-WORKFLOW-MISSION-SMALL","CONCERT-WORKFLOW-EXECUTION","CONCERT-WORKFLOW-CODE-QUALITY","CONCERT-WORKFLOW-REVIEW-CYCLE","CONCERT-WORKFLOW-OBSERVABILITY","CONCERT-WORKFLOW-SELF-IMPROVEMENT"];

describe("workflow files", () => {
  for (const wf of EXPECTED_WORKFLOWS) {
    it(`${wf}.md exists with managed header`, () => {
      const wfPath = path.join(TEMPLATES_DIR, "docs", "concert", "workflows", `${wf}.md`);
      expect(fs.existsSync(wfPath)).toBe(true);
      const content = fs.readFileSync(wfPath, "utf-8");
      expect(content).toMatch(/<!-- AUTO-GENERATED BY CONCERT/);
    });
  }
});

// ======================================================================
// 6. Skill files
// ======================================================================

const EXPECTED_SKILLS = ["typescript-standards","cli-ux-guidelines","agent-authoring"];

describe("skill files", () => {
  for (const skill of EXPECTED_SKILLS) {
    it(`${skill}/SKILL.md exists with managed header and frontmatter`, () => {
      const skillPath = path.join(TEMPLATES_DIR, "docs", "concert", "skills", skill, "SKILL.md");
      expect(fs.existsSync(skillPath)).toBe(true);
      const content = fs.readFileSync(skillPath, "utf-8");
      expect(content).toMatch(/<!-- AUTO-GENERATED BY CONCERT/);
      expect(content).toContain("name:");
      expect(content).toContain("applies_to:");
    });
  }
});

// ======================================================================
// 7. GitHub Actions workflow files
// ======================================================================

describe("GitHub Actions workflow files", () => {
  it("concert-ci.yml exists with managed header", () => {
    const ciPath = path.join(TEMPLATES_DIR, ".github", "workflows", "concert-ci.yml");
    expect(fs.existsSync(ciPath)).toBe(true);
    const content = fs.readFileSync(ciPath, "utf-8");
    expect(content).toMatch(/# AUTO-GENERATED BY CONCERT/);
    expect(content).toContain("concert/**");
  });

  it("concert-version-check.yml exists with managed header", () => {
    const vcPath = path.join(TEMPLATES_DIR, ".github", "workflows", "concert-version-check.yml");
    expect(fs.existsSync(vcPath)).toBe(true);
    const content = fs.readFileSync(vcPath, "utf-8");
    expect(content).toMatch(/# AUTO-GENERATED BY CONCERT/);
  });
});

// ======================================================================
// 8. Configuration and state files
// ======================================================================

describe("configuration and state files", () => {
  it("templates/concert.jsonc is parseable", () => {
    const configPath = path.join(TEMPLATES_DIR, "concert.jsonc");
    expect(fs.existsSync(configPath)).toBe(true);
    const content = fs.readFileSync(configPath, "utf-8");
    const errors: jsonc.ParseError[] = [];
    jsonc.parse(content, errors);
    expect(errors).toHaveLength(0);
  });

  it("templates/docs/concert/state.json is valid JSON", () => {
    const statePath = path.join(TEMPLATES_DIR, "docs", "concert", "state.json");
    expect(fs.existsSync(statePath)).toBe(true);
    const content = fs.readFileSync(statePath, "utf-8");
    expect(() => JSON.parse(content)).not.toThrow();
  });

  it("templates/CLAUDE.md has CONCERT:START and CONCERT:END markers", () => {
    const claudePath = path.join(TEMPLATES_DIR, "CLAUDE.md");
    expect(fs.existsSync(claudePath)).toBe(true);
    const content = fs.readFileSync(claudePath, "utf-8");
    expect(content).toContain("CONCERT:START");
    expect(content).toContain("CONCERT:END");
  });

  it("templates/docs/concert/README.md exists", () => {
    expect(fs.existsSync(path.join(TEMPLATES_DIR, "docs", "concert", "README.md"))).toBe(true);
  });

  it("templates/docs/concert/missions/.gitkeep exists", () => {
    expect(fs.existsSync(path.join(TEMPLATES_DIR, "docs", "concert", "missions", ".gitkeep"))).toBe(true);
  });
});

// ======================================================================
// 9. Cross-reference consistency
// ======================================================================

describe("cross-reference consistency", () => {
  it("every GitHub stub references an existing agent definition", () => {
    const stubsDir = path.join(TEMPLATES_DIR, ".github", "agents");
    const agentsDir = path.join(TEMPLATES_DIR, "docs", "concert", "agents");
    if (!fs.existsSync(stubsDir)) return;
    const stubs = fs.readdirSync(stubsDir).filter((f) => f.endsWith(".agent.md"));
    for (const stub of stubs) {
      const agentName = stub.replace(".agent.md", "");
      const agentPath = path.join(agentsDir, `${agentName}.md`);
      expect(fs.existsSync(agentPath), `Missing agent for stub: ${stub}`).toBe(true);
    }
  });

  it("state.json default has all required fields", () => {
    const statePath = path.join(TEMPLATES_DIR, "docs", "concert", "state.json");
    const state = JSON.parse(fs.readFileSync(statePath, "utf-8"));
    for (const field of ["mission","branch","pr_number","stage","pipeline","phases_completed","tasks_completed","commits","cost","blockers","telemetry","failure_log","history","next_steps"]) {
      expect(state, `Missing: ${field}`).toHaveProperty(field);
    }
  });
});

// ======================================================================
// 10. No accidental large files
// ======================================================================

describe("template file sizes", () => {
  it("no file in templates exceeds 50KB", () => {
    function checkSize(dir: string): void {
      if (!fs.existsSync(dir)) return;
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          checkSize(fullPath);
        } else {
          const stats = fs.statSync(fullPath);
          expect(stats.size, `${fullPath} exceeds 50KB`).toBeLessThan(50 * 1024);
        }
      }
    }
    checkSize(TEMPLATES_DIR);
  });
});
