import { describe, it, expect } from 'vitest';
import {
  extractHeaderVersion,
  compareVersions,
  needsUpdate,
  isManagedFile,
} from '../lib/version.js';

describe('extractHeaderVersion', () => {
  it('finds version in markdown header', () => {
    const content = `<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->
# Agent file
rest of content`;
    expect(extractHeaderVersion(content)).toBe('0.1.0');
  });

  it('finds version in YAML comment header', () => {
    const content = `# AUTO-GENERATED BY CONCERT v1.2.3 — DO NOT EDIT.
name: concert-status
rest: content`;
    expect(extractHeaderVersion(content)).toBe('1.2.3');
  });

  it('returns null for no header', () => {
    const content = `# Regular comment
no version here`;
    expect(extractHeaderVersion(content)).toBeNull();
  });

  it('only checks first 5 lines', () => {
    const content = `line 1
line 2
line 3
line 4
line 5
<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->
line 7`;
    expect(extractHeaderVersion(content)).toBeNull();
  });
});

describe('compareVersions', () => {
  it('correctly compares equal versions', () => {
    expect(compareVersions('1.0.0', '1.0.0')).toBe(0);
    expect(compareVersions('0.1.5', '0.1.5')).toBe(0);
  });

  it('correctly compares less-than versions', () => {
    expect(compareVersions('0.1.0', '1.0.0')).toBe(-1);
    expect(compareVersions('1.0.0', '1.1.0')).toBe(-1);
    expect(compareVersions('1.1.0', '1.1.1')).toBe(-1);
  });

  it('correctly compares greater-than versions', () => {
    expect(compareVersions('1.0.0', '0.9.9')).toBe(1);
    expect(compareVersions('2.0.0', '1.9.9')).toBe(1);
    expect(compareVersions('1.2.0', '1.1.9')).toBe(1);
  });

  it('handles different-length versions (missing parts default to 0)', () => {
    expect(compareVersions('1.0', '1.0.0')).toBe(0);
    expect(compareVersions('1', '1.0.0')).toBe(0);
    expect(compareVersions('1.0.1', '1.0')).toBe(1);
  });
});

describe('needsUpdate', () => {
  it('returns true for no header', () => {
    expect(needsUpdate('# Regular file\nno header', '0.1.0')).toBe(true);
  });

  it('returns true for older version', () => {
    const content = '<!-- AUTO-GENERATED BY CONCERT v0.0.9 — DO NOT EDIT. -->\nrest';
    expect(needsUpdate(content, '0.1.0')).toBe(true);
  });

  it('returns false for same version', () => {
    const content = '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nrest';
    expect(needsUpdate(content, '0.1.0')).toBe(false);
  });

  it('returns false for newer version (file is ahead)', () => {
    const content = '<!-- AUTO-GENERATED BY CONCERT v0.2.0 — DO NOT EDIT. -->\nrest';
    expect(needsUpdate(content, '0.1.0')).toBe(false);
  });
});

describe('isManagedFile', () => {
  it('detects managed files with markdown header', () => {
    const content = '<!-- AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT. -->\nrest';
    expect(isManagedFile(content)).toBe(true);
  });

  it('detects managed files with YAML header', () => {
    const content = '# AUTO-GENERATED BY CONCERT v0.1.0 — DO NOT EDIT.\nname: agent';
    expect(isManagedFile(content)).toBe(true);
  });

  it('returns false for non-managed files', () => {
    const content = '# Regular markdown file\nno managed header';
    expect(isManagedFile(content)).toBe(false);
  });
});
