#!/usr/bin/env bash
# Sync live concert files into templates/ for npm packaging.
# Source of truth: docs/concert/, .claude/commands/concert/, .github/agents/
# Run automatically before build via `npm run prebuild`.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "Syncing live files → templates/..."

# Agents
rm -rf "$ROOT/templates/docs/concert/agents"
cp -r "$ROOT/docs/concert/agents" "$ROOT/templates/docs/concert/agents"

# Workflows
rm -rf "$ROOT/templates/docs/concert/workflows"
cp -r "$ROOT/docs/concert/workflows" "$ROOT/templates/docs/concert/workflows"

# Skills (only copy the ones that ship as defaults)
rm -rf "$ROOT/templates/docs/concert/skills"
mkdir -p "$ROOT/templates/docs/concert/skills"
for skill in cli-ux-guidelines typescript-standards; do
  if [ -d "$ROOT/docs/concert/skills/$skill" ]; then
    cp -r "$ROOT/docs/concert/skills/$skill" "$ROOT/templates/docs/concert/skills/$skill"
  fi
done

# Claude Code commands (prepend managed header if missing)
MANAGED_HEADER='<!-- AUTO-GENERATED BY CONCERT — DO NOT EDIT.
     This file is managed by Concert and will be overwritten on \`concert update\`. -->'

rm -rf "$ROOT/templates/.claude/commands"
mkdir -p "$ROOT/templates/.claude/commands"
for cmd in "$ROOT/.claude/commands/concert/"*.md; do
  dest="$ROOT/templates/.claude/commands/$(basename "$cmd")"
  if grep -q "AUTO-GENERATED BY CONCERT" "$cmd"; then
    cp "$cmd" "$dest"
  else
    printf '%s\n\n' "$MANAGED_HEADER" > "$dest"
    cat "$cmd" >> "$dest"
  fi
done

# GitHub agent stubs
rm -rf "$ROOT/templates/.github/agents"
mkdir -p "$ROOT/templates/.github/agents"
cp "$ROOT/.github/agents/concert-"*.agent.md "$ROOT/templates/.github/agents/"

echo "Done. Synced agents, workflows, skills, commands, and GitHub agents."
